export const categories = ["Just-JB Partywear", "Just-JB Luxe"];

export const shopBanner = "/assets/banner/shop-banner.png";

export const products = [
  {
    id: "party-1",
    name: "Beige Sleeveless Embellished Dress with long Tassels at hem",
    price: 100,
    image: [
      "/assets/products/partywear/product-beige_sleeveless_embellishes_dress_with_long_tassels_at_hem-1.png",
      "/assets/products/partywear/product-beige_sleeveless_embellishes_dress_with_long_tassels_at_hem-2.jpg",
      "/assets/products/partywear/product-beige_sleeveless_embellishes_dress_with_long_tassels_at_hem-3.jpg",
      "/assets/products/partywear/product-beige_sleeveless_embellishes_dress_with_long_tassels_at_hem-4.jpg",
    ],
    category: "Just-JB Partywear",
    sizes: ["S", "M"],
    description: "A stunning beige dress with intricate embellishments and long tassels, perfect for any party.",
  },
  {
    id: "party-2",
    name: "Golden Sequined Crisscross Haltere Neck Backless Jumpsuit",
    price: 150,
    image: [
      "/assets/products/partywear/product-golden_sequined_crisscross_haltere_neck_backless_jumpsuit-1.png",
      "/assets/products/partywear/product-golden_sequined_crisscross_haltere_neck_backless_jumpsuit-2.png",
    ],
    category: "Just-JB Partywear",
    sizes: ["S", "M", "L"],
    description: "Shine bright in this golden sequined jumpsuit with a crisscross halter neck and backless design.",
  },
  {
    id: "party-3",
    name: "Ivory Sleeveless Tinsel Midi Dress",
    price: 120,
    image: [
      "/assets/products/partywear/product-ivory_sleeveless_tinsel_midi_dress-1.png",
      "/assets/products/partywear/product-ivory_sleeveless_tinsel_midi_dress-2.png",
      "/assets/products/partywear/product-ivory_sleeveless_tinsel_midi_dress-3.png",
    ],
    category: "Just-JB Partywear",
    sizes: ["XS", "S", "M"],
    description: "Elegant ivory midi dress with tinsel detailing, perfect for a sophisticated evening.",
  },
  {
    id: "party-4",
    name: "Midnight Blue Plunge High Slit Dress",
    price: 130,
    image: [
      "/assets/products/partywear/product-midnight_blue_plunge_high_slit_dress-1.png",
      "/assets/products/partywear/product-midnight_blue_plunge_high_slit_dress-2.png",
      "/assets/products/partywear/product-midnight_blue_plunge_high_slit_dress-3.png",
    ],
    category: "Just-JB Partywear",
    sizes: ["M", "L"],
    description: "Turn heads in this midnight blue dress with a plunging neckline and high slit.",
  },
  {
    id: "party-5",
    name: "Pink Roseline Sequence Noodle Strap Mini Dress",
    price: 110,
    image: [
      "/assets/products/partywear/product-pink_roseline_sequence_noodle_strap_mini_dress-1.png",
      "/assets/products/partywear/product-pink_roseline_sequence_noodle_strap_mini_dress-2.png",
      "/assets/products/partywear/product-pink_roseline_sequence_noodle_strap_mini_dress-3.png",
      "/assets/products/partywear/product-pink_roseline_sequence_noodle_strap_mini_dress-4.png",
    ],
    category: "Just-JB Partywear",
    sizes: ["S", "M", "L"],
    description: "Cute and flirty pink mini dress with roseline sequins and noodle straps.",
  },
  {
    id: "party-6",
    name: "Silver Sequence One-Sleeve One-Shoulder High Slit Evening Dress",
    price: 140,
    image: [
      "/assets/products/partywear/product-silver_sequence_one-sleeve_one-shoulder_high_slit_evening_dress-1.png",
      "/assets/products/partywear/product-silver_sequence_one-sleeve_one-shoulder_high_slit_evening_dress-2.png",
      "/assets/products/partywear/product-silver_sequence_one-sleeve_one-shoulder_high_slit_evening_dress-3.png",
    ],
    category: "Just-JB Partywear",
    sizes: ["M", "L"],
    description: "Dazzle in this silver sequined evening dress with a one-sleeve, one-shoulder design and high slit.",
  },
  {
    id: "party-7",
    name: "Spangle Mini Woven Strappy Dress with Tassel Hem",
    price: 115,
    image: [
      "/assets/products/partywear/product-spangle_mini_woven_strappy_dress_with_tassel_hem-1.png",
      "/assets/products/partywear/product-spangle_mini_woven_strappy_dress_with_tassel_hem-2.png",
      "/assets/products/partywear/product-spangle_mini_woven_strappy_dress_with_tassel_hem-3.png",
      "/assets/products/partywear/product-spangle_mini_woven_strappy_dress_with_tassel_hem-4.png",
    ],
    category: "Just-JB Partywear",
    sizes: ["XS", "S", "M"],
    description: "A chic mini dress with spangle details, woven strappy design, and tassel hem.",
  },
  {
    id: "luxe-1",
    name: "Ruffled Snowy One-Sleeve One-Shoulder Cutout Waist Dress",
    price: 200,
    image: [
      "/assets/products/luxe/product-ruffled_snowy_one-sleeve_one-shoulder_cutout_waist_dress-1.png",
      "/assets/products/luxe/product-ruffled_snowy_one-sleeve_one-shoulder_cutout_waist_dress-2.png",
      "/assets/products/luxe/product-ruffled_snowy_one-sleeve_one-shoulder_cutout_waist_dress-3.png",
    ],
    category: "Just-JB Luxe",
    sizes: ["S", "M"],
    description: "A snowy white dress with ruffled details, one-sleeve, one-shoulder cutout waist design.",
  },
  {
    id: "luxe-2",
    name: "Luxury Frosted Smock One Sleeve Kaftan Gown",
    price: 250,
    image: [
      "/assets/products/luxe/product-luxury_frosted_smock_one_sleeve_kaftan_gown-1.png",
      "/assets/products/luxe/product-luxury_frosted_smock_one_sleeve_kaftan_gown-2.png",
    ],
    category: "Just-JB Luxe",
    sizes: ["M", "L"],
    description: "A luxurious frosted smock kaftan gown with one sleeve, perfect for a grand event.",
  },
  {
    id: "luxe-3",
    name: "Heavily Embellished Mauve Halter Neck Ruched Gown",
    price: 275,
    image: [
      "/assets/products/luxe/product-heavily_embellished_mauve_halter_neck_ruched_gown-1.png",
      "/assets/products/luxe/product-heavily_embellished_mauve_halter_neck_ruched_gown-2.png",
    ],
    category: "Just-JB Luxe",
    sizes: ["XS", "S"],
    description: "A mauve gown with heavy embellishments, halter neck, and ruched design.",
  },
  {
    id: "luxe-4",
    name: "Green Embellished Sweet Heart Neckline Noodle Strap Gown",
    price: 220,
    image: [
      "/assets/products/luxe/product-green_embellished_sweet_heart_neckline_noodle_strap_gown-1.png",
      "/assets/products/luxe/product-green_embellished_sweet_heart_neckline_noodle_strap_gown-2.png",
    ],
    category: "Just-JB Luxe",
    sizes: ["S", "M"],
    description: "A green gown with sweet heart neckline, noodle straps, and intricate embellishments.",
  },
  {
    id: "luxe-5",
    name: "Enchanted Grey One-Shoulder Embellished Ruched Gown",
    price: 230,
    image: [
      "/assets/products/luxe/product-enchanted_grey_one-shoulder_embellished_ruched_gown-1.png",
      "/assets/products/luxe/product-enchanted_grey_one-shoulder_embellished_ruched_gown-2.png",
    ],
    category: "Just-JB Luxe",
    sizes: ["M", "L"],
    description: "An enchanted grey gown with one-shoulder design, embellished and ruched details.",
  },
  {
    id: "luxe-6",
    name: "Elegant Black Diamante One-Shoulder Plumes Dress",
    price: 260,
    image: [
      "/assets/products/luxe/product-elegant_black_diamante_one-shoulder_plumes_dress-1.png",
      "/assets/products/luxe/product-elegant_black_diamante_one-shoulder_plumes_dress-2.png",
    ],
    category: "Just-JB Luxe",
    sizes: ["L", "XL"],
    description: "An elegant black dress with diamante details, one-shoulder design, and plumes.",
  },
  {
    id: "luxe-7",
    name: "Ebony Plunger Halter Neck High Slit Dress",
    price: 240,
    image: [
      "/assets/products/luxe/product-ebony_plunger_halter_neck_high_slit_dress-1.png",
      "/assets/products/luxe/product-ebony_plunger_halter_neck_high_slit_dress-2.png",
    ],
    category: "Just-JB Luxe",
    sizes: ["S", "M"],
    description: "An ebony dress with plunger halter neck and high slit, perfect for a luxurious evening.",
  },
  {
    id: "luxe-8",
    name: "Bandeau Peacock Teal High Slit Mermaid Silk Gown",
    price: 280,
    image: [
      "/assets/products/luxe/product-bandeau_peacock_teal_high_slit_mermaid_silk_gown-1.png",
      "/assets/products/luxe/product-bandeau_peacock_teal_high_slit_mermaid_silk_gown-2.png",
    ],
    category: "Just-JB Luxe",
    sizes: ["S", "M", "L"],
    description: "A peacock teal silk gown with bandeau top, high slit, and mermaid silhouette.",
  },
  {
    id: "holiday-1",
    name: "Festive Red Velvet Dress",
    price: 90,
    image: [
      "/assets/products/holiday/product-festive_red_velvet_dress-1.png",
      "/assets/products/holiday/product-festive_red_velvet_dress-2.png",
    ],
    category: "Holiday Season",
    sizes: ["S", "M", "L"],
    description: "A festive red velvet dress, perfect for holiday celebrations.",
  },
  {
    id: "holiday-2",
    name: "Green Sequin Holiday Gown",
    price: 120,
    image: [
      "/assets/products/holiday/product-green_sequin_holiday_gown-1.png",
      "/assets/products/holiday/product-green_sequin_holiday_gown-2.png",
    ],
    category: "Holiday Season",
    sizes: ["M", "L"],
    description: "A green sequin gown, ideal for holiday parties and events.",
  },
  {
    id: "holiday-3",
    name: "Gold Sparkle Mini Dress",
    price: 110,
    image: [
      "/assets/products/holiday/product-gold_sparkle_mini_dress-1.png",
      "/assets/products/holiday/product-gold_sparkle_mini_dress-2.png",
    ],
    category: "Holiday Season",
    sizes: ["XS", "S", "M"],
    description: "A gold sparkle mini dress, perfect for festive occasions.",
  },
  {
    id: "holiday-4",
    name: "Silver Glitter Evening Gown",
    price: 150,
    image: [
      "/assets/products/holiday/product-silver_glitter_evening_gown-1.png",
      "/assets/products/holiday/product-silver_glitter_evening_gown-2.png",
    ],
    category: "Holiday Season",
    sizes: ["S", "M", "L"],
    description: "A silver glitter evening gown, perfect for glamorous holiday events.",
  },
  {
    id: "holiday-5",
    name: "Blue Velvet Holiday Dress",
    price: 95,
    image: [
      "/assets/products/holiday/product-blue_velvet_holiday_dress-1.png",
      "/assets/products/holiday/product-blue_velvet_holiday_dress-2.png",
    ],
    category: "Holiday Season",
    sizes: ["M", "L"],
    description: "A blue velvet dress, perfect for holiday gatherings.",
  },
  {
    id: "holiday-6",
    name: "White Snowflake Gown",
    price: 130,
    image: [
      "/assets/products/holiday/product-white_snowflake_gown-1.png",
      "/assets/products/holiday/product-white_snowflake_gown-2.png",
    ],
    category: "Holiday Season",
    sizes: ["S", "M"],
    description: "A white gown with snowflake details, perfect for winter holidays.",
  },
  {
    id: "holiday-7",
    name: "Black Sequin Party Dress",
    price: 105,
    image: [
      "/assets/products/holiday/product-black_sequin_party_dress-1.png",
      "/assets/products/holiday/product-black_sequin_party_dress-2.png",
    ],
    category: "Holiday Season",
    sizes: ["S", "M", "L"],
    description: "A black sequin dress, perfect for holiday parties.",
  },
  {
    id: "holiday-8",
    name: "Purple Satin Holiday Gown",
    price: 140,
    image: [
      "/assets/products/holiday/product-purple_satin_holiday_gown-1.png",
      "/assets/products/holiday/product-purple_satin_holiday_gown-2.png",
    ],
    category: "Holiday Season",
    sizes: ["M", "L"],
    description: "A purple satin gown, perfect for elegant holiday events.",
  },
  {
    id: "holiday-9",
    name: "Emerald Green Holiday Dress",
    price: 115,
    image: [
      "/assets/products/holiday/product-emerald_green_holiday_dress-1.png",
      "/assets/products/holiday/product-emerald_green_holiday_dress-2.png",
    ],
    category: "Holiday Season",
    sizes: ["XS", "S", "M"],
    description: "An emerald green dress, perfect for festive holiday gatherings.",
  },
  {
    id: "holiday-10",
    name: "Red and Gold Festive Gown",
    price: 160,
    image: [
      "/assets/products/holiday/product-red_and_gold_festive_gown-1.png",
      "/assets/products/holiday/product-red_and_gold_festive_gown-2.png",
    ],
    category: "Holiday Season",
    sizes: ["S", "M", "L"],
    description: "A red and gold gown, perfect for festive holiday celebrations.",
  },
];
export const getProductsByCategory = (category: string) => {
  return products.filter((product) => product.category === category);
};

export const getProductById = (id: string) => {
  return products.find((product) => product.id === id);
};
