import type { Metadata } from "next";
import { Navbar } from "@/components/navbar";

import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import ModalProvider from "@/components/modal-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ModalProvider />
      <body className={cn(inter.className, "bg-snow")}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
