// Dependencies
import type { Metadata } from "next";

// Utils
import { cn } from "@/lib/utils";

// Fonts
import { Inter } from "next/font/google";

// CSS
import "./globals.css";

// Fonts
import { poppins } from "@/lib/direct-fonts";

// UI Components
import { Toaster } from "@/components/ui/toaster"; // For showing alerts
import PageLoader from "@/components/loader/page-loader";
import WhatsappBtn from "@/components/whatsapp-btn";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(poppins.className, "bg-snow flex flex-col min-h-screen")}>
        {/* <PageLoader /> */}
        <WhatsappBtn />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
