// Dependencies
import type { Metadata } from "next";

// CSS
import "../../globals.css";

// UI Components
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer";
import Navbar1 from "@/components/navbar/navbar-1";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar1 />
      {children}
      <Footer />
    </>
  );
}
